### ISSUE TITLE
Port the module to Synapse's pluggable modules

### ISSUE THREAD

**Issue by Iamsomeguy** [matrix-org/matrix-synapse-ldap3#133]
**Is your feature request related to a problem? Please describe.**
The password_providers: module interface has been deprecated and matrix-synapse-ldap3 does not seem to support the new generic module interface.

**Describe the solution you'd like**
Could you please port the module to the new generic module interface.

**Describe alternatives you've considered**

**Additional context**
Here is the error I get if I try to use the module with the generic interface:
```
2021-11-03 08:37:00,307 - root - 345 - WARNING - main - ***** STARTING SERVER *****
2021-11-03 08:37:00,308 - root - 346 - WARNING - main - Server /opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.46.0
2021-11-03 08:37:00,484 - synapse.app._base - 214 - CRITICAL - sentinel - Error during startup
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/_base.py", line 199, in wrapper
    await cb(*args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", line 374, in start
    await _base.start(hs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/_base.py", line 390, in start
    module(config=config, api=module_api)
TypeError: __init__() got an unexpected keyword argument 'api'
```

**Comment by reivilibre** [comment]
For context:
The password provider module interface was ported to the module API in https://github.com/matrix-org/synapse/pull/10548.

We don't seem to have explicitly called out the deprecation, but it *has* been removed from the config file and the documentation page for it is deprecated.

Thanks for opening this issue!

**Comment by callahad** [comment]
@reivilibre has agreed to take a look at this more closely; thank you :)

**Comment by richvdh** [comment]
handy link: https://matrix-org.github.io/synapse/latest/modules/porting_legacy_module.html

remember to maintain compatibility with the old interface, so as to avoid breaking existing deploys.
