### ISSUE TITLE
Logging Error on User Creation

### ISSUE THREAD

**Issue by chrissphinx** [matrix-org/matrix-synapse-ldap3#38]
```
2017-09-27 10:30:05,507 - twisted - 131 - ERROR - POST-1321- Traceback (most recent call last):
2017-09-27 10:30:05,508 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
2017-09-27 10:30:05,510 - twisted - 131 - ERROR - POST-1321-     if self.shouldRollover(record):
2017-09-27 10:30:05,510 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
2017-09-27 10:30:05,511 - twisted - 131 - ERROR - POST-1321-     msg = "%s\n" % self.format(record)
2017-09-27 10:30:05,512 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
2017-09-27 10:30:05,514 - twisted - 131 - ERROR - POST-1321-     return fmt.format(record)
2017-09-27 10:30:05,515 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
2017-09-27 10:30:05,515 - twisted - 131 - ERROR - POST-1321-     record.message = record.getMessage()
2017-09-27 10:30:05,516 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
2017-09-27 10:30:05,517 - twisted - 131 - ERROR - POST-1321-     msg = msg % self.args
2017-09-27 10:30:05,518 - twisted - 131 - ERROR - POST-1321- TypeError: %d format: a number is required, not str
2017-09-27 10:30:05,519 - twisted - 131 - ERROR - POST-1321- Logged from file ldap_auth_provider.py, line 202
2017-09-27 10:30:05,520 - twisted - 131 - ERROR - POST-1321- Traceback (most recent call last):
2017-09-27 10:30:05,521 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
2017-09-27 10:30:05,522 - twisted - 131 - ERROR - POST-1321-     msg = self.format(record)
2017-09-27 10:30:05,522 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
2017-09-27 10:30:05,523 - twisted - 131 - ERROR - POST-1321-     return fmt.format(record)
2017-09-27 10:30:05,524 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
2017-09-27 10:30:05,525 - twisted - 131 - ERROR - POST-1321-     record.message = record.getMessage()
2017-09-27 10:30:05,525 - twisted - 131 - ERROR - POST-1321-   File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
2017-09-27 10:30:05,526 - twisted - 131 - ERROR - POST-1321-     msg = msg % self.args
2017-09-27 10:30:05,527 - twisted - 131 - ERROR - POST-1321- TypeError: %d format: a number is required, not str
2017-09-27 10:30:05,528 - twisted - 131 - ERROR - POST-1321- Logged from file ldap_auth_provider.py, line 202
2017-09-27 10:30:05,796 - synapse.handlers.auth - 442 - INFO - POST-1321- Logging in user @test:domain.com on device XXXXXXXXXX
```

I think there is a problem with these lines: https://github.com/matrix-org/matrix-synapse-ldap3/blob/7276440021f6fb2c877d7a7e46cfff1ed53ac608/ldap_auth_provider.py#L199-L203

Especially since this comment says: https://github.com/matrix-org/matrix-synapse-ldap3/blob/7276440021f6fb2c877d7a7e46cfff1ed53ac608/ldap_auth_provider.py#L84

**Comment by richvdh** [comment]
dup #51
