### ISSUE TITLE
Synapse 0.25 appears to have broken this package

### ISSUE THREAD

**Issue by neutralinsomniac** [matrix-org/matrix-synapse-ldap3#42]
It looks like the API changed for auth providers from what I can tell. This is the stack trace I get when trying to auth against our LDAP server

```
2017-11-16 08:57:01,220 - synapse.http.server - 139 - ERROR - POST-42- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7f54af13f090>: <SynapseRequest at 0x7f54ac35bb48 method=POST uri=/_matrix/client/r0/login? clientproto=HTTP/1.1 site=8008>
Traceback (most recent call last):
  File "/home/user/.synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/home/user/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/user/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/.synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 257, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/user/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/user/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/.synapse/local/lib/python2.7/site-packages/synapse/rest/client/v1/login.py", line 154, in on_POST
    result = yield self._do_other_login(login_submission)
  File "/home/user/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/.synapse/local/lib/python2.7/site-packages/synapse/rest/client/v1/login.py", line 224, in _do_other_login
    login_submission,
ValueError: too many values to unpack

```

**Comment by neutralinsomniac** [comment]
This appears to have been fixed in synapse itself with this: https://github.com/matrix-org/synapse/commit/56e2a4333e0da7ab08b035ccd80cce95324fa745

Closing this issue.
