### ISSUE TITLE
Problem with LDAP Login

### ISSUE THREAD

**Issue by SysRam** [matrix-org/matrix-synapse-ldap3#54]
Dear Support

We newly installed your matrix synapse server. After that, we installed the LDAP3 Module. 

But when we activate the plugin, we get the following Error-Message:

` Traceback (most recent call last):
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Oct 29 07:22:40 matrix-riot python[2661]:     "__main__", fname, loader, pkg_name)
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Oct 29 07:22:40 matrix-riot python[2661]:     exec code in run_globals
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 582, in <module>
Oct 29 07:22:40 matrix-riot python[2661]:     main()
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 577, in main
Oct 29 07:22:40 matrix-riot python[2661]:     hs = setup(sys.argv[1:])
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 323, in setup
Oct 29 07:22:40 matrix-riot python[2661]:     config_options,
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 341, in load_or_generate_config
Oct 29 07:22:40 matrix-riot python[2661]:     generate_keys=generate_keys,
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 385, in read_config_files
Oct 29 07:22:40 matrix-riot python[2661]:     self.invoke_all("read_config", config)
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 165, in invoke_all
Oct 29 07:22:40 matrix-riot python[2661]:     results.append(getattr(cls, name)(self, *args, **kargs))
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/dist-packages/synapse/config/password_auth_providers.py", line 48, in read_config
Oct 29 07:22:40 matrix-riot python[2661]:     "config": provider['config'],
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/dist-packages/synapse/util/module_loader.py", line 32, in load_module
Oct 29 07:22:40 matrix-riot python[2661]:     module = importlib.import_module(module)
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
Oct 29 07:22:40 matrix-riot python[2661]:     __import__(name)
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/local/lib/python2.7/dist-packages/ldap_auth_provider.py", line 19, in <module>
Oct 29 07:22:40 matrix-riot python[2661]:     import ldap3
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/local/lib/python2.7/dist-packages/ldap3/__init__.py", line 138, in <module>
Oct 29 07:22:40 matrix-riot python[2661]:     from .core.connection import Connection
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 37, in <module>
Oct 29 07:22:40 matrix-riot python[2661]:     from ..extend import ExtendedOperationsRoot
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/__init__.py", line 45, in <module>
Oct 29 07:22:40 matrix-riot python[2661]:     from .standard.whoAmI import WhoAmI
Oct 29 07:22:40 matrix-riot python[2661]:   File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/standard/whoAmI.py", line 27, in <module>
Oct 29 07:22:40 matrix-riot python[2661]:     from pyasn1.type.univ import NoValue
Oct 29 07:22:40 matrix-riot python[2661]: ImportError: cannot import name NoValue`

Here is the configuration of the ldap module (Line 572 till 585):
`password_providers:
     - module: "ldap_auth_provider.LdapAuthProvider"
       config:
         enabled: true
         uri: "ldaps://server:7636"
         start_tls: true
         base: "dc=domain,dc=net"
         attributes:
            uid: "uid"
            mail: "mailPrimaryAddress"
            name: "displayName"
         bind_dn: "authenication_name"
         bind_password: "authentication_pass"
         filter: "(objectClass=posixAccount)"
`

Many thanks in advance for your help, solving that issue.

Kind Regards

STAR AG IT Department

**Comment by SysRam** [comment]
Hi

I fixed the issue.. over

> pip list | grep pyasn

i found, that the installed version was pyasn1 (0.1.9)

i then did a update to the latest version: 

>  pip install pyasn1 -U

Now the latest version is installed (pyasn1 (0.4.4)) and the server starts normally 

Issue can be closed

Kind Regards

STAR AG IT Department
