### ISSUE TITLE
Tests not compatible with python 3

### ISSUE THREAD

**Issue by matoro** [matrix-org/matrix-synapse-ldap3#73]
Tests fail with the following:

```
tests ...                                                               [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/twisted/trial/runner.py", line 803, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "/usr/lib/python3.6/site-packages/twisted/trial/runner.py", line 732, in findByName
    obj = reflect.namedAny(name)
  File "/usr/lib/python3.6/site-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python3.6/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/var/tmp/portage/dev-python/matrix-synapse-ldap3-0.1.3/work/matrix-synapse-ldap3-0.1.3/tests/__init__.py", line 8, in <module>
    from cStringIO import StringIO
builtins.ModuleNotFoundError: No module named 'cStringIO'
```

The `cStringIO` module has been removed in python 3:  https://stackoverflow.com/a/28204760

**Comment by scarabeusiv** [comment]
Well the bigger problem is that if you fix this issue it reveals the code itself should not be working under python3.
The trivial patchie for the tests execution [py3tests.txt](https://github.com/matrix-org/matrix-synapse-ldap3/files/3808158/py3tests.txt)
