### ISSUE TITLE
Problem with LDAP (samba4) login -- User does not exist

### ISSUE THREAD

**Issue by tmatthaeus** [matrix-org/matrix-synapse-ldap3#80]
I am trying to authenticate a user against our LDAP / Samba4. But I got the error message, that the user is not existing.

If I create a different user (which exists in the LDAP too) with "register_new_matrix_user -c /etc/matrix-synapse/homeserver.yaml http://localhost:8008" with a dummy password which is different then the password of the LDAP, then the user can login with the LDAP password.

But I am sure, there must exists an option to authenticate against the LDAP without creating manually every user.... Hopefully someone can help me. The last closed issues regarding to this problem are not helping me :(

I am using the version "1.6.0+buster1"

Here is my LDAP configuration in homeserver.yaml:

```
password_providers:
    - module: "ldap_auth_provider.LdapAuthProvider"
      config:
        enabled: true
        uri: "ldap://dc.domain.lan:389"
        start_tls: false
        base: "dc=dc,dc=domain,dc=lan"
        attributes:
           uid: "sAMAccountName"
           mail: "mail"
           name: "givenName"
        bind_dn: "cn=readonly-admin,cn=users,dc=dc,dc=domain,dc=lan"
        bind_password: "PASSWORD"
#       filter: "(&(ObjectClass=user)(kopanoAccount=1))"
```

And here is the output from the Logfile

> 2019-11-28 20:34:21,216 - synapse.rest.client.v1.login - 179 - INFO - POST-0 - Got login request with identifier: {'type': 'm.id.user', 'user': 'testuser'}, medium: None, address: None, user: None
> 2019-11-28 20:34:21,216 - ldap_auth_provider - 91 - DEBUG - POST-0 - Attempting LDAP connection with ldap://dc.domain.lan:389
> 2019-11-28 20:34:21,217 - ldap_auth_provider - 342 - DEBUG -  - Established LDAP connection in search mode: ldap://dc.domain.lan:389 - cleartext - user: cn=ro-admin,cn=users,dc=DC,dc=domain,dc=lan - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
> 2019-11-28 20:34:21,277 - ldap_auth_provider - 375 - DEBUG -  - LDAP search filter: (sAMAccountName=testuser)
> 2019-11-28 20:34:21,281 - ldap_auth_provider - 393 - DEBUG -  - LDAP search found dn: CN=testuser,OU=IT,OU=Verwaltung,DC=dc,DC=domain,DC=lan
> 2019-11-28 20:34:21,282 - ldap_auth_provider - 287 - DEBUG -  - Established LDAP connection in simple bind mode: ldap://dc.domain.lan:389 - cleartext - user: CN=testuser,OU=IT,OU=Verwaltung,DC=dc,DC=domain,DC=lan - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
> 2019-11-28 20:34:21,344 - ldap_auth_provider - 301 - DEBUG -  - LDAP Bind successful in simple bind mode.
> 2019-11-28 20:34:21,344 - ldap_auth_provider - 119 - DEBUG -  - LDAP auth method authenticated search returned: True (conn: ldap://dc.domain.lan:389 - cleartext - user: CN=testuser,OU=IT,OU=Verwaltung,DC=dc,DC=domain,DC=lan - not lazy - bound - open - <local: 194.95.6.40:59738 - remote: 192.168.16.21:389> - tls not started - listening - SyncStrategy - internal decoder)
> 2019-11-28 20:34:21,344 - ldap_auth_provider - 133 - INFO -  - User authenticated against LDAP server: ldap://dc.domain.lan:389 - cleartext - user: CN=testuser,OU=IT,OU=Verwaltung,DC=dc,DC=domain,DC=lan - not lazy - bound - open - <local: 194.95.6.40:59738 - remote: 192.168.16.21:389> - tls not started - listening - SyncStrategy - internal decoder
> 2019-11-28 20:34:21,345 - synapse.storage._base - 494 - WARNING -  - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
> 2019-11-28 20:34:21,345 - synapse.storage._base - 533 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
> 2019-11-28 20:34:21,346 - synapse.handlers.auth - 552 - WARNING -  - Attempted to login as @testuser:matrix.domain.de but they do not exist
> 2019-11-28 20:34:21,347 - ldap_auth_provider - 163 - DEBUG -  - ldap registration filter: (sAMAccountName=testuser)
> 2019-11-28 20:34:21,350 - synapse.module_api - 100 - WARNING -  - Using deprecated ModuleApi.register which creates a dummy user device.
> 2019-11-28 20:34:21,350 - synapse.storage._base - 494 - WARNING -  - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
> 2019-11-28 20:34:21,351 - synapse.storage._base - 533 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
> 2019-11-28 20:34:21,352 - synapse.storage._base - 494 - WARNING -  - Starting db txn 'register_user' from sentinel context
> 2019-11-28 20:34:21,352 - synapse.storage._base - 533 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
> 2019-11-28 20:34:21,355 - synapse.http.server - 109 - ERROR -  - Failed handle request via 'LoginRestServlet': <XForwardedForRequest at 0x7f81198fada0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site=8008>
> Traceback (most recent call last):
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
>     await h(self, request)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/server.py", line 326, in _async_render
>     callback_return = await callback_return
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/rest/client/v1/login.py", line 152, in on_POST
>     result = yield self._do_other_login(login_submission)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/rest/client/v1/login.py", line 284, in _do_other_login
>     identifier["user"], login_submission
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/auth.py", line 622, in validate_login
>     is_valid = yield provider.check_password(qualified_user_id, password)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/ldap_auth_provider.py", line 193, in check_password
>     yield self.account_handler.register(localpart=localpart)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/module_api/__init__.py", line 102, in register
>     user_id = yield self.register_user(localpart, displayname, emails)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/register.py", line 209, in register_user
>     address=address,
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 504, in runInteraction
>     **kwargs
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 552, in runWithConnection
>     self._db_pool.runWithConnection(inner_func, *args, **kwargs)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
>     result = inContext.theWork()
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
>     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, *args, **kw)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
>     return func(*args,**kw)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
>     compat.reraise(excValue, excTraceback)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
>     raise exception.with_traceback(traceback)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
>     result = func(conn, *args, **kw)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 549, in inner_func
>     return func(conn, *args, **kwargs)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 421, in _new_transaction
>     r = func(txn, *args, **kwargs)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/data_stores/main/registration.py", line 1077, in _register_user
>     (user_id_obj.localpart, create_profile_with_displayname),
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 152, in execute
>     self._do_execute(self.txn.execute, sql, *args)
>   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 178, in _do_execute
>     return func(sql, *args)
> sqlite3.IntegrityError: UNIQUE constraint failed: profiles.user_id

**Comment by tmatthaeus** [comment]
De-Installed everything and re-installed from scratch new. Now it is working. I think there was some issue in my configuration.
