### ISSUE TITLE
Login error with synapse 1.15.0 (TypeError: 'coroutine' object is not iterable)

### ISSUE THREAD

**Issue by gramakri** [matrix-org/matrix-synapse-ldap3#92]
Tried to update our matrix install from 1.14.0 to 1.15.0. It crashes with the following error:

```
14:42:52 - 2020-06-11 21:42:52,523 - synapse.http.server - 113 - ERROR -  - Failed handle request via 'LoginRestServlet': <XForwardedForRequest at 0x7f89689119e8 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.1' site=8008>
14:42:52 - Traceback (most recent call last):
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
14:42:52 -     result = g.send(result)
14:42:52 - StopIteration
14:42:52 - 
14:42:52 - During handling of the above exception, another exception occurred:
14:42:52 - 
14:42:52 - Traceback (most recent call last):
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
14:42:52 -     result = g.send(result)
14:42:52 - StopIteration
14:42:52 - 
14:42:52 - During handling of the above exception, another exception occurred:
14:42:52 - 
14:42:52 - Traceback (most recent call last):
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
14:42:52 -     result = g.send(result)
14:42:52 - StopIteration
14:42:52 - 
14:42:52 - During handling of the above exception, another exception occurred:
14:42:52 - 
14:42:52 - Traceback (most recent call last):
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
14:42:52 -     result = g.send(result)
14:42:52 - StopIteration
14:42:52 - 
14:42:52 - During handling of the above exception, another exception occurred:
14:42:52 - 
14:42:52 - Traceback (most recent call last):
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
14:42:52 -     result = g.send(result)
14:42:52 - StopIteration: @girish:cloudron.fun
14:42:52 - 
14:42:52 - During handling of the above exception, another exception occurred:
14:42:52 - 
14:42:52 - Traceback (most recent call last):
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
14:42:52 -     await h(self, request)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/synapse/http/server.py", line 350, in _async_render
14:42:52 -     callback_return = await callback_return
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/synapse/rest/client/v1/login.py", line 149, in on_POST
14:42:52 -     result = await self._do_other_login(login_submission)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/synapse/rest/client/v1/login.py", line 264, in _do_other_login
14:42:52 -     identifier["user"], login_submission
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/synapse/handlers/auth.py", line 722, in validate_login
14:42:52 -     is_valid = await provider.check_password(qualified_user_id, password)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
14:42:52 -     result = result.throwExceptionIntoGenerator(g)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
14:42:52 -     return g.throw(self.type, self.value, self.tb)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/ldap_auth_provider.py", line 180, in check_password
14:42:52 -     user_id = yield self.register_user(localpart, givenName, mail)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
14:42:52 -     result = result.throwExceptionIntoGenerator(g)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
14:42:52 -     return g.throw(self.type, self.value, self.tb)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/ldap_auth_provider.py", line 291, in register_user
14:42:52 -     localpart=localpart, displayname=name, emails=emails,
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
14:42:52 -     result = g.send(result)
14:42:52 -   File "/app/code/env/lib/python3.6/site-packages/synapse/module_api/__init__.py", line 113, in register
14:42:52 -     _, access_token = yield self.register_device(user_id)
14:42:52 - TypeError: 'coroutine' object is not iterable
```

**Comment by richvdh** [comment]
I think this is a synapse bug; moving it accordingly.
